[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python -c "from database import Database; db = Database(); db.init_db()"']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120'
